version: '3'
services:
  api:
    image: system-configurator
    name: system-configurator:1.0.0
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
  web-cli:
    image: system-configurator
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge